# Generated by Django 5.2.4 on 2025-07-30 02:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0002_marca_proveedor_producto_stock_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='categoria',
        ),
    ]
